### PR TITLE
Added missing 'PendingIntent.FLAG_MUTABLE' and fixed gradle

### PR DESCRIPTION
**Pull request by fquirin**
- Added missing 'PendingIntent.FLAG_MUTABLE' to Notification and Builder Java files for Android
- Fixed gradle build file to use 'implementation' and updated 'appShortcutBadgerVersion'

### CODE REVIEW

**Comment by bhandaribhumin** [comment]
@timkellypa When will you merge this?

**Comment by 123dma** [comment]
Hello, I added these changes in an internal version that I use here and although the error no longer occurs I was only able to receive the scheduled notification after adding the permission in the App manifest.

 `<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />`

**Comment by fquirin** [comment]
yes, I think that is required now. I've always had it in my Cordova config, so I might not have noticed any changes. I'm not sure how to add it to the plugin automatically though? Any suggestions?

**Comment by GitToTheHub** [comment]
@fquirin 
Thank you, for adding the fixes here!
I saw some repository-replacements from the original"katzer"-repository to your repository or to the "bhandaribhumin"-repository in the files "CHANGELOG.md", "package.json" and "plugin.xml". Are they necessary?

**Comment by GitToTheHub** [comment]
@fquirin 
It would be great, if you could create a merge-branch, which would contain the changes :)

**Comment by fquirin** [comment]
I just realized that the latest changes accidentally ended up in this old PR when I updated my repository 🙈 
The original plan was to create a new branch to clean up the README, package.json, etc.., revert the comments and changes that where only meant for the fork and then push everything to the original 'katzer' repository.

Here is a bit more info about the changes: https://github.com/katzer/cordova-plugin-local-notifications/issues/1990

Maybe I'll find some time to do this in the next days, but it is not really at the top of my to-do list ^^.

**Comment by fquirin** [comment]
I decided to quickly put something together ^^:

https://github.com/katzer/cordova-plugin-local-notifications/pull/2000 and https://github.com/timkellypa/cordova-plugin-local-notifications/pull/10

I'm going to close this one in favor of a new PR.

**Comment by GitToTheHub** [comment]
Cool, thank you for your work! :)

**Pull request closed without merging**
